#include<iostream>
using namespace std;
int main(){
//     cout<<"HELLO PRINCE"<<endl;
// int const a = 10;// by using const the value is been fix and cant be changed
// //a =78;
// cout<<a<<endl;
// int b;
// cout<<"Enter the number\n";
// cin>>b;
// cout<<"The number is "<<b<<endl;
// cout<<"The sum of a and b is "<<a+b<<endl;
// ************************************************************************************
//  long long int a;//to store a mobile number
// cin>>a;
// cout<<"a = "<<a<<endl;
// ***************************************************************************************
cout<<endl<<"Welcome"<<endl;
float celsius = 32.0;
float formula;
formula = (celsius*9/5)+32;
cout<<formula<<endl;

    return 0;
}

